In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

In [3]:
42/(np.sqrt(52)*np.sqrt(34))

0.9988681377244375

In [5]:
1-0.999

0.0010000000000000009

In [4]:
50/(np.sqrt(52)*np.sqrt(73))

0.8115343414514945

In [6]:
1-0.812

0.18799999999999994

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
#Usage of TFIDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [9]:
import pandas as pd

In [10]:
ds = pd.read_csv("/content/drive/My Drive/Recommendation System Mahesh Anand/fashion_store.csv")

In [ ]:
ds.head()

id                                        description
0   1  Active classic boxers - There's a reason why o...
1   2  Active sport boxer briefs - Skinning up Glory ...
2   3  Active sport briefs - These superbreathable no...
3   4  Alpine guide pants - Skin in, climb ice, switc...
4   5  Alpine wind jkt - On high ridges, steep ice an...

In [ ]:
ds.tail(5)

id                                        description
495  496  Cap 2 bottoms - Cut loose from the maddening c...
496  497  Cap 2 crew - This crew takes the edge off fick...
497  498  All-time shell - No need to use that morning T...
498  499  All-wear cargo shorts - All-Wear Cargo Shorts ...
499  500  All-wear shorts - Time to simplify? Our All-We...

In [ ]:
ds['description'][4]

'Alpine wind jkt - On high ridges, steep ice and anything alpine, this jacket serves as a true "best of all worlds" staple. It excels as a stand-alone shell for blustery rock climbs, cool-weather trail runs and high-output ski tours. And then, when conditions have you ice and alpine climbing, it functions as a lightly insulated windshirt on the approach, as well as a frictionless midlayer when it\'s time to bundle up and tie-in. The polyester ripstop shell with a Deluge DWR (durable water repellent) treatment sheds snow and blocks wind, while the smooth, lightly brushed hanging mesh liner wicks moisture, dries fast, and doesn\'t bind to your baselayers. Superlight stretch-woven underarm panels enhance breathability and allow for unimpaired arm motion, and the two hand pockets close with zippers. A drawcord hem, elastic cuffs, a heat-transfer reflective logo and a regular-coil, center-front zipper with DWR finish round out the features. Updated this season for an improved fit. Recyclabl

In [ ]:
ds.tail()

id                                        description
495  496  Cap 2 bottoms - Cut loose from the maddening c...
496  497  Cap 2 crew - This crew takes the edge off fick...
497  498  All-time shell - No need to use that morning T...
498  499  All-wear cargo shorts - All-Wear Cargo Shorts ...
499  500  All-wear shorts - Time to simplify? Our All-We...

In [ ]:
ds['description'][3]

'Alpine guide pants - Skin in, climb ice, switch to rock, traverse a knife-edge ridge and boogie back down - these durable, weather-resistant and breathable soft-shell pants keep stride on every mountain endeavor. The midweight stretch-woven polyester won\'t restrict your moves, and the brushed interior maintains next-to-skin comfort. A 2-way zippered fly keeps things easy with a harness on, and the gusseted, zippered cuffs have 2-position snaps and tie-down loops. With water-resistant zippered pockets: two front, two thigh, one back hip. Recyclable through the Common Threads Recycling Program.<br><br><b>Details:</b><ul> <li>Durable stretch-woven polyester (47% recycled) with DWR (durable water repellent) finish is water- and wind-resistant and highly breathable</li> <li>Brushed interior for next-to-skin comfort</li> <li>Waistband has belt loops and elastic on back</li> <li>2-way zippered fly</li> <li>"External pockets: two front slash, two glued-on thigh, one back hip - all with highl

In [11]:
tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0.0, stop_words='english')
#min_df is used for removing terms that appear too infrequently
#min_df = 0.01 means "ignore terms that appear in less than 1% of the documents
tfidf_matrix = tf.fit_transform(ds['description'])

In [ ]:
tfidf_matrix.shape

(500, 52262)

In [ ]:
type(tfidf_matrix)

scipy.sparse._csr.csr_matrix

In [12]:
cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)

In [13]:
cosine_similarities.shape

(500, 500)

In [ ]:
cosine_similarities

array([[1.        , 0.10110642, 0.06487353, ..., 0.06097409, 0.06546914,
        0.06955608],
       [0.10110642, 1.        , 0.4181664 , ..., 0.03550042, 0.06936414,
        0.06480538],
       [0.06487353, 0.4181664 , 1.        , ..., 0.03402428, 0.0455137 ,
        0.05038512],
       ...,
       [0.06097409, 0.03550042, 0.03402428, ..., 1.        , 0.04187121,
        0.04958298],
       [0.06546914, 0.06936414, 0.0455137 , ..., 0.04187121, 1.        ,
        0.36281626],
       [0.06955608, 0.06480538, 0.05038512, ..., 0.04958298, 0.36281626,
        1.        ]])

In [ ]:
cosine_similarities[0]

array([1.        , 0.10110642, 0.06487353, 0.05420526, 0.04566789,
       0.04303635, 0.03836477, 0.03348336, 0.06532573, 0.02368301,
       0.05799294, 0.07367418, 0.02995859, 0.0445901 , 0.04851878,
       0.06006065, 0.0275863 , 0.16769458, 0.22037921, 0.1322533 ,
       0.14137642, 0.10338036, 0.10166674, 0.09677083, 0.13879533,
       0.05296341, 0.04753103, 0.0476742 , 0.06065872, 0.0609826 ,
       0.02809675, 0.05731604, 0.0282521 , 0.06172938, 0.04318156,
       0.04935251, 0.06176504, 0.0383252 , 0.03620475, 0.0596439 ,
       0.04740036, 0.02545151, 0.05714612, 0.04306838, 0.05131491,
       0.06862622, 0.04713296, 0.02338129, 0.02139625, 0.02271573,
       0.02924247, 0.05434761, 0.03281554, 0.02201043, 0.04419009,
       0.0545336 , 0.06156667, 0.05987447, 0.04452303, 0.11800705,
       0.10290746, 0.06858677, 0.0596259 , 0.06545195, 0.05866774,
       0.05204685, 0.02430063, 0.0494294 , 0.02066233, 0.05724809,
       0.04733546, 0.05243107, 0.05816163, 0.03620532, 0.04474

In [40]:
#by default smallest to largest
cosine_similarities[0].argsort()

array([331, 489, 318, 424, 433,  68,  48, 438, 370, 133,  53,  49,  47,
       351, 395,   9,  82,  66, 237, 136,  41, 348, 421,  85, 430, 434,
       454, 196, 467,  84, 113, 420, 211, 273, 393,  16, 326, 134, 149,
       381,  30,  32, 455, 485, 112, 425, 240,  50,  93, 354, 366, 153,
       152, 252, 243, 337,  12,  98, 129, 132, 423,  78, 392, 419, 344,
        83, 157, 429, 128,  79, 428, 141, 456, 280, 130,  52,  95, 341,
       135, 219, 404, 220, 338,   7, 221, 241, 343, 448, 353, 463, 350,
       106, 110, 315, 289, 367, 274, 140, 397, 299, 306, 270, 436, 260,
       251, 242, 147,  38,  73, 388, 417,  80, 253, 292, 464, 191, 278,
       281, 382, 154, 122, 190,  92,  37,   6, 142, 197, 312, 409, 363,
       214, 383, 209, 246, 148, 303, 144, 313, 225, 471, 290, 218, 250,
       262, 255, 435, 377, 181,  77, 161, 120, 298, 378, 224, 473, 231,
       257, 477, 198, 375, 478, 217, 100, 139, 297, 102, 178, 400, 189,
       232,   5, 131,  43, 239, 254, 472,  34, 261, 182, 205, 29

In [41]:
similar_indices = cosine_similarities[200].argsort()[-6:-1]

In [42]:
similar_indices

array([ 86,  87, 199, 264, 259])

In [34]:
ds['description'][200]

'Merino 1 tank - Finespun and cool enough to lower the temperature of open trail runs, heated crags and the Laiki street market, this silky-soft yet highly durable jersey-knit tank is made with 63% merino wool spun around an all-recycled polyester (37%) core. Super-comfortable on its own in warm temperatures or beneath layers in cooler ones, it offers great technical performance: naturally resisting odor, moving moisture away from the skin and improving dry times, regulating body temperature, and maintaining a consistent stretch. The neck - with a smooth, self-fabric binding -invites ventilation but still covers a bra. We slow-wash our merino for next-to-skin softness. Machine-wash cold; lay flat to dry. Recyclable through the Common Threads Recycling Program.<br><br><b>Details:</b><ul> <li>"Slow-washed merino wool resists odor naturally, insulates even when wet, is durable, stretches and provides superior performance and softness"</li> <li>16.5 micron-gauge yarn and jersey-knit constr

In [48]:
ds['description'][264][:18]

'Merino 1 t-shirt -'

In [37]:
from sklearn.neighbors import NearestNeighbors
model_knn = NearestNeighbors(metric = 'cosine')
model_knn.fit(tfidf_matrix)

NearestNeighbors(metric='cosine')

In [43]:
distances, indices = model_knn.kneighbors(tfidf_matrix[200, :], n_neighbors = 6)

In [ ]:
type(indices)

numpy.ndarray

In [ ]:
distances

array([[0.        , 0.77962079, 0.83061049, 0.83230542, 0.83514472,
        0.85187385]])

In [45]:
indices

array([[200, 259, 264, 199,  87,  86]])

In [44]:
indices[0,1:]

array([259, 264, 199,  87,  86])